### ISSUE TITLE
[Checklist] Service 테스트

### ISSUE THREAD

**Issue by khabh** [khabh/GoalTracker#2]

**Comment by khabh** [comment]
### 테스트 코드 작성 ###

- [ ] ChecklistHistoryService 테스트 코드 작성
- [ ] ChecklistService 테스트 코드 작성
- [ ]  ChecklistStateService 테스트 코드 작성
